name: Build and Deploy

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout the code of the repo
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: restore dependencies
        run: dotnet restore

      - name: build
        run: dotnet build -c Release --no-restore
        
      - name: test
        run: dotnet test
        
      - name: Publish
        run: dotnet publish -c Release -o ./out
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ./out      
  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build

    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp
          
      - name: Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'BugBustersWeb'
          slot-name: 'Production'
          package: .
